"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { ArrowLeft, Plus, Download, Share2, Eye, Trash2 } from "lucide-react"
import { formatCurrency } from "@/lib/form-utils"

interface Receipt {
  id: string
  title: string
  amount: number
  recipient: string
  date: string
  reference: string
  description: string
  template: string
}

interface ReceiptGeneratorProps {
  onBack: () => void
}

export function ReceiptGenerator({ onBack }: ReceiptGeneratorProps) {
  const [receipts, setReceipts] = useState<Receipt[]>([
    {
      id: "1",
      title: "Transfer Receipt",
      amount: 30000,
      recipient: "Pedro Banabas",
      date: "2023-05-19",
      reference: "TXN123456789",
      description: "Transfer to other bank",
      template: "standard",
    },
  ])

  const [showCreateModal, setShowCreateModal] = useState(false)
  const [showPreviewModal, setShowPreviewModal] = useState(false)
  const [previewReceipt, setPreviewReceipt] = useState<Receipt | null>(null)
  const [newReceipt, setNewReceipt] = useState({
    title: "",
    amount: "",
    recipient: "",
    description: "",
    template: "standard",
  })

  const templates = [
    { id: "standard", name: "Standard Receipt" },
    { id: "detailed", name: "Detailed Receipt" },
    { id: "minimal", name: "Minimal Receipt" },
  ]

  const handleCreateReceipt = () => {
    if (newReceipt.title && newReceipt.amount && newReceipt.recipient) {
      const receipt: Receipt = {
        id: Date.now().toString(),
        title: newReceipt.title,
        amount: Number.parseFloat(newReceipt.amount),
        recipient: newReceipt.recipient,
        date: new Date().toISOString().split("T")[0],
        reference: `TXN${Date.now()}`,
        description: newReceipt.description,
        template: newReceipt.template,
      }
      setReceipts([...receipts, receipt])
      setNewReceipt({
        title: "",
        amount: "",
        recipient: "",
        description: "",
        template: "standard",
      })
      setShowCreateModal(false)
    }
  }

  const handlePreview = (receipt: Receipt) => {
    setPreviewReceipt(receipt)
    setShowPreviewModal(true)
  }

  const handleDownload = (receipt: Receipt) => {
    // Simulate download
    console.log("Downloading receipt:", receipt.id)
  }

  const handleShare = (receipt: Receipt) => {
    // Simulate share
    console.log("Sharing receipt:", receipt.id)
  }

  const handleDelete = (id: string) => {
    setReceipts(receipts.filter((r) => r.id !== id))
  }

  const generateReceiptHTML = (receipt: Receipt) => {
    return `
      <div style="max-width: 400px; margin: 0 auto; padding: 20px; font-family: Arial, sans-serif; border: 1px solid #ddd;">
        <div style="text-align: center; margin-bottom: 20px;">
          <h2 style="color: #004A9F; margin: 0;">Ecobank Nigeria</h2>
          <p style="margin: 5px 0; color: #666;">Transaction Receipt</p>
        </div>
        
        <div style="border-top: 2px solid #004A9F; padding-top: 15px;">
          <h3 style="margin: 0 0 15px 0;">${receipt.title}</h3>
          
          <div style="margin-bottom: 10px;">
            <strong>Amount:</strong> ₦${formatCurrency(receipt.amount)}
          </div>
          
          <div style="margin-bottom: 10px;">
            <strong>Recipient:</strong> ${receipt.recipient}
          </div>
          
          <div style="margin-bottom: 10px;">
            <strong>Date:</strong> ${new Date(receipt.date).toLocaleDateString()}
          </div>
          
          <div style="margin-bottom: 10px;">
            <strong>Reference:</strong> ${receipt.reference}
          </div>
          
          ${
            receipt.description
              ? `
          <div style="margin-bottom: 10px;">
            <strong>Description:</strong> ${receipt.description}
          </div>
          `
              : ""
          }
          
          <div style="margin-top: 20px; padding-top: 15px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 12px;">
            Generated by Ecobank Mobile App
          </div>
        </div>
      </div>
    `
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white px-4 py-4 flex items-center justify-between border-b">
        <Button variant="ghost" size="icon" onClick={onBack}>
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <h1 className="text-lg font-semibold">Receipt Generator</h1>
        <Button size="icon" className="bg-[#004A9F] hover:bg-[#003875]" onClick={() => setShowCreateModal(true)}>
          <Plus className="h-4 w-4" />
        </Button>
      </div>

      <div className="px-4 py-6 space-y-6">
        {/* Statistics */}
        <div className="grid grid-cols-3 gap-3">
          <Card className="text-center">
            <CardContent className="p-4">
              <div className="text-lg font-bold text-[#004A9F]">{receipts.length}</div>
              <div className="text-xs text-gray-600">Total Receipts</div>
            </CardContent>
          </Card>
          <Card className="text-center">
            <CardContent className="p-4">
              <div className="text-lg font-bold text-[#00B2A9]">
                ₦{formatCurrency(receipts.reduce((sum, r) => sum + r.amount, 0))}
              </div>
              <div className="text-xs text-gray-600">Total Amount</div>
            </CardContent>
          </Card>
          <Card className="text-center">
            <CardContent className="p-4">
              <div className="text-lg font-bold text-[#A4D233]">{templates.length}</div>
              <div className="text-xs text-gray-600">Templates</div>
            </CardContent>
          </Card>
        </div>

        {/* Receipts List */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Generated Receipts</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {receipts.map((receipt) => (
              <div key={receipt.id} className="p-4 bg-gray-50 rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <div className="font-medium">{receipt.title}</div>
                  <div className="flex items-center gap-1">
                    <Button variant="ghost" size="icon" onClick={() => handlePreview(receipt)}>
                      <Eye className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleDownload(receipt)}>
                      <Download className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleShare(receipt)}>
                      <Share2 className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleDelete(receipt.id)}>
                      <Trash2 className="h-4 w-4 text-red-500" />
                    </Button>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <div className="text-gray-600">Amount</div>
                    <div className="font-medium">₦{formatCurrency(receipt.amount)}</div>
                  </div>
                  <div>
                    <div className="text-gray-600">Recipient</div>
                    <div className="font-medium">{receipt.recipient}</div>
                  </div>
                  <div>
                    <div className="text-gray-600">Date</div>
                    <div className="font-medium">{new Date(receipt.date).toLocaleDateString()}</div>
                  </div>
                  <div>
                    <div className="text-gray-600">Reference</div>
                    <div className="font-medium">{receipt.reference}</div>
                  </div>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>

      {/* Create Receipt Modal */}
      <Dialog open={showCreateModal} onOpenChange={setShowCreateModal}>
        <DialogContent className="max-w-sm mx-auto">
          <DialogHeader>
            <DialogTitle>Create New Receipt</DialogTitle>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <Label htmlFor="receipt-title">Receipt Title</Label>
              <Input
                id="receipt-title"
                value={newReceipt.title}
                onChange={(e) => setNewReceipt({ ...newReceipt, title: e.target.value })}
                placeholder="Enter receipt title"
              />
            </div>

            <div>
              <Label htmlFor="receipt-amount">Amount</Label>
              <Input
                id="receipt-amount"
                type="number"
                value={newReceipt.amount}
                onChange={(e) => setNewReceipt({ ...newReceipt, amount: e.target.value })}
                placeholder="Enter amount"
              />
            </div>

            <div>
              <Label htmlFor="receipt-recipient">Recipient</Label>
              <Input
                id="receipt-recipient"
                value={newReceipt.recipient}
                onChange={(e) => setNewReceipt({ ...newReceipt, recipient: e.target.value })}
                placeholder="Enter recipient name"
              />
            </div>

            <div>
              <Label htmlFor="receipt-description">Description (Optional)</Label>
              <Textarea
                id="receipt-description"
                value={newReceipt.description}
                onChange={(e) => setNewReceipt({ ...newReceipt, description: e.target.value })}
                placeholder="Enter description"
                rows={2}
              />
            </div>

            <div>
              <Label htmlFor="receipt-template">Template</Label>
              <Select
                value={newReceipt.template}
                onValueChange={(value) => setNewReceipt({ ...newReceipt, template: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {templates.map((template) => (
                    <SelectItem key={template.id} value={template.id}>
                      {template.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="flex gap-2 pt-4">
              <Button variant="outline" onClick={() => setShowCreateModal(false)} className="flex-1">
                Cancel
              </Button>
              <Button onClick={handleCreateReceipt} className="flex-1 bg-[#004A9F] hover:bg-[#003875]">
                Create Receipt
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Preview Modal */}
      <Dialog open={showPreviewModal} onOpenChange={setShowPreviewModal}>
        <DialogContent className="max-w-md mx-auto max-h-[80vh] overflow-hidden">
          <DialogHeader>
            <DialogTitle>Receipt Preview</DialogTitle>
          </DialogHeader>

          {previewReceipt && (
            <div className="space-y-4 overflow-y-auto">
              <div
                className="border rounded-lg p-4 bg-white"
                dangerouslySetInnerHTML={{ __html: generateReceiptHTML(previewReceipt) }}
              />

              <div className="flex gap-2">
                <Button variant="outline" onClick={() => handleDownload(previewReceipt)} className="flex-1">
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
                <Button onClick={() => handleShare(previewReceipt)} className="flex-1 bg-[#00B2A9] hover:bg-[#008A82]">
                  <Share2 className="h-4 w-4 mr-2" />
                  Share
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
